# Clone, build, and deploy, restarting nginx if necessary. This playbook must
# be run after provision and configure, and is used to deploy and build the
# specified commit (overridable via extra vars) on the server.

- hosts: all
  sudo: yes
  vars:
    commit: master
    force: false
  roles:
    - deploy
