# Get the box up and running. These tasks run before the box is configured
# or the project is cloned or built. All system dependencies should be
# installed here.

- name: add keys to apt
  apt_key: url={{item}} state=present
  with_items: apt_keys

- name: add ppas to apt
  apt_repository: repo="{{item}}" state=present update_cache=yes
  with_items: apt_ppas

- name: install apt packages
  apt: name={{item}} state=latest update_cache=yes
  with_items: apt_packages

- name: update npm to latest
  npm: name=npm state=latest global=yes

- name: install global npm modules
  npm:
    name={{item.name}}
    state=present
    version={{ item.version | default(omit) }}
    global=yes
  with_items: npm_global_modules
